---
- hosts: all
  remote_user: ubuntu
  tasks:
      # upload ssh key
      - authorized_key:
              user: anatoliy
              state: present
              manage_dir: yes
              key: "{{ lookup('file', '/home/anatoliy/.ssh/id_rsa.pub') }}"

- name: Gathering facts
  hosts: all

  become: yes
  gather_facts: yes

- name: Install docker
  hosts: docker
  become: yes
  gather_facts: no
  roles:
    - docker

- name: Install magicComparator
  hosts: api
  become: yes
  gather_facts: no
  roles:
    - magicComparator