---

- name: Gathering facts
  hosts: all

  become: yes
  gather_facts: yes

- name: Install docker
  hosts: docker
  become: yes
  gather_facts: no
  roles:
    - docker

- name: Install magicComparator
  hosts: api
  become: yes
  gather_facts: no
  roles:
    - magicComparator