"""fix default value for type

Revision ID: b0c80306eef3
Revises: e429cf8e57c2
Create Date: 2022-06-17 22:27:56.060748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0c80306eef3'
down_revision = 'e429cf8e57c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
